#!/usr/bin/env bash
# Installs and configures HAProxy with round robin load balancing

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 13.222.212.192:80 check
    server web-02 44.201.158.84:80 check
EOF

service haproxy restart
