#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing "Holberton School"

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx start
